#ifndef _MODELER_GLOBALS_H
#define _MODELER_GLOBALS_H

#ifndef M_PI
#define M_PI 3.141592653589793238462643383279502
#endif

// This is a list of the controls for the SampleModel
// We'll use these constants to access the values 
// of the controls from the user interface.
/*
enum SampleModelControls
{ 
	XPOS, YPOS, ZPOS, HEIGHT, ROTATE, NUMCONTROLS
};
*/

enum HandModelControls
{
	XPOS, YPOS, ZPOS,
	XROTATE, YROTATE, ZROTATE,
	THUMB_TIP_XROTATE, THUMB_TIP_YROTATE, THUMB_TIP_ZROTATE,
	THUMB_ROOT_XROTATE, THUMB_ROOT_YROTATE, THUMB_ROOT_ZROTATE,
	INDEX_TIP_XROTATE, INDEX_TIP_YROTATE, INDEX_TIP_ZROTATE,
	INDEX_MID_XROTATE, INDEX_MID_YROTATE, INDEX_MID_ZROTATE,
	INDEX_ROOT_XROTATE, INDEX_ROOT_YROTATE, INDEX_ROOT_ZROTATE,
	MIDDLE_TIP_XROTATE, MIDDLE_TIP_YROTATE, MIDDLE_TIP_ZROTATE,
	MIDDLE_MID_XROTATE, MIDDLE_MID_YROTATE, MIDDLE_MID_ZROTATE,
	MIDDLE_ROOT_XROTATE, MIDDLE_ROOT_YROTATE, MIDDLE_ROOT_ZROTATE,
	RING_TIP_XROTATE, RING_TIP_YROTATE, RING_TIP_ZROTATE,
	RING_MID_XROTATE, RING_MID_YROTATE, RING_MID_ZROTATE,
	RING_ROOT_XROTATE, RING_ROOT_YROTATE, RING_ROOT_ZROTATE,
	LITTLE_TIP_XROTATE, LITTLE_TIP_YROTATE, LITTLE_TIP_ZROTATE,
	LITTLE_MID_XROTATE, LITTLE_MID_YROTATE, LITTLE_MID_ZROTATE,
	LITTLE_ROOT_XROTATE, LITTLE_ROOT_YROTATE, LITTLE_ROOT_ZROTATE,
	NUMCONTROLS
};

// Colors
#define COLOR_RED		1.0f, 0.0f, 0.0f
#define COLOR_GREEN		0.0f, 1.0f, 0.0f
#define COLOR_BLUE		0.0f, 0.0f, 1.0f

// We'll be getting the instance of the application a lot; 
// might as well have it as a macro.
#define VAL(x) (ModelerApplication::Instance()->GetControlValue(x))

#endif